### ISSUE TITLE
Tests randomly fail every so often

### ISSUE THREAD

**Issue by koden-km** [rinq/rinq-go#161]
Tests randomly fail every so often and not always at the same place.
Running tests again with no changes will work.

go version go1.9.1 linux/amd64

Test output error dump:
```
•! Panic [0.054 seconds]
peer (functional)
/home/kevin/go/src/github.com/rinq/rinq-go/src/rinqamqp/peer_functional_test.go:15
  Session
  /home/kevin/go/src/github.com/rinq/rinq-go/src/rinqamqp/peer_functional_test.go:35
    returns a session even if the peer is stopped [It]
    /home/kevin/go/src/github.com/rinq/rinq-go/src/rinqamqp/peer_functional_test.go:54

    Test Panicked
    Exception (405) Reason: "RESOURCE_LOCKED - cannot obtain exclusive access to locked queue '74CA.rsp' in vhost '/'"
    /usr/lib/go-1.9/src/runtime/panic.go:491

    Full Stack Trace
    	/usr/lib/go-1.9/src/runtime/panic.go:491 +0x283
    github.com/rinq/rinq-go/src/internal/functest.NewPeer(0x0, 0x0)
    	/home/kevin/go/src/github.com/rinq/rinq-go/src/internal/functest/peer.go:35 +0x185
    github.com/rinq/rinq-go/src/rinqamqp_test.glob..func1.4.3()
    	/home/kevin/go/src/github.com/rinq/rinq-go/src/rinqamqp/peer_functional_test.go:55 +0x26
    github.com/rinq/rinq-go/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc4201649c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    	/home/kevin/go/src/github.com/rinq/rinq-go/src/rinqamqp/ginkgo_test.go:12 +0x64
    testing.tRunner(0xc42033c0f0, 0xa9b958)
    	/usr/lib/go-1.9/src/testing/testing.go:746 +0xd0
    created by testing.(*T).Run
    	/usr/lib/go-1.9/src/testing/testing.go:789 +0x2de
```

**Comment by jmalloc** [comment]
Is it always an AMQP `RESOURCE_LOCKED` exception?

**Comment by jmalloc** [comment]
I also haven't been able to reproduce this yet.  I'm running my tests in a loop with

```bash
while true; do make; done
```

Are you able to reproduce this reliably by running the test suite repeatedly?

I suspect the issue is related to the `functest` package which is used to initialise peers for the functional test suites.

**Comment by koden-km** [comment]
I'm pretty sure its not always a `RESOURCE_LOCKED` exception. I will update this issue again when I see the next one happen. It was happening fairly frequently the other day, about 1 in every 5 runs. That one above has been the only one so far today though.

**Comment by jmalloc** [comment]
Does it happen more often when you're offline? I'm wondering if the slow-downs caused by the DNS issues we talked about are slowing down Rabbit from cleaning up old queues, or something like that.

**Comment by koden-km** [comment]
I don't think I've seen it at all while offline, but I do rarely run tests when offline due to the slowness.

**Comment by koden-km** [comment]
I just got another one that is a `RESOURCE_LOCKED` error.

This one was running on my branch 128-include-trace-id.
The one above was on master.

```
•! Panic [0.206 seconds]
peer (functional)
/home/kevin/go/src/github.com/rinq/rinq-go/src/rinqamqp/peer_functional_test.go:15
  ID
  /home/kevin/go/src/github.com/rinq/rinq-go/src/rinqamqp/peer_functional_test.go:26
    returns a valid peer ID [It]
    /home/kevin/go/src/github.com/rinq/rinq-go/src/rinqamqp/peer_functional_test.go:27

    Test Panicked
    Exception (405) Reason: "RESOURCE_LOCKED - cannot obtain exclusive access to locked queue '1CEE.rsp' in vhost '/'"
    /usr/lib/go-1.9/src/runtime/panic.go:491

    Full Stack Trace
    	/usr/lib/go-1.9/src/runtime/panic.go:491 +0x283
    github.com/rinq/rinq-go/src/internal/functest.NewPeer(0x8, 0xa9d710)
    	/home/kevin/go/src/github.com/rinq/rinq-go/src/internal/functest/peer.go:35 +0x185
    github.com/rinq/rinq-go/src/internal/functest.SharedPeer(0x0, 0x0)
    	/home/kevin/go/src/github.com/rinq/rinq-go/src/internal/functest/peer.go:22 +0xa4
    github.com/rinq/rinq-go/src/rinqamqp_test.glob..func1.3.1()
    	/home/kevin/go/src/github.com/rinq/rinq-go/src/rinqamqp/peer_functional_test.go:28 +0x26
    github.com/rinq/rinq-go/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc420066a20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    	/home/kevin/go/src/github.com/rinq/rinq-go/src/rinqamqp/ginkgo_test.go:12 +0x64
    testing.tRunner(0xc4202f60f0, 0xa9b960)
    	/usr/lib/go-1.9/src/testing/testing.go:746 +0xd0
    created by testing.(*T).Run
    	/usr/lib/go-1.9/src/testing/testing.go:789 +0x2de
```

**Comment by jmalloc** [comment]
Let me know also if it's always a `<peerID>.rsp` queue.

**Comment by koden-km** [comment]
Another just now:
```
•! Panic in Spec Setup (BeforeEach) [0.021 seconds]
revision (functional)
/home/kevin/go/src/github.com/rinq/rinq-go/src/internal/remotesession/revision_functional_test.go:15
  Get [BeforeEach]
  /home/kevin/go/src/github.com/rinq/rinq-go/src/internal/remotesession/revision_functional_test.go:61
    returns an attribute created on the owning peer
    /home/kevin/go/src/github.com/rinq/rinq-go/src/internal/remotesession/revision_functional_test.go:90

    Test Panicked
    Exception (405) Reason: "RESOURCE_LOCKED - cannot obtain exclusive access to locked queue '00AD.rsp' in vhost '/'"
    /usr/lib/go-1.9/src/runtime/panic.go:491

    Full Stack Trace
    	/usr/lib/go-1.9/src/runtime/panic.go:491 +0x283
    github.com/rinq/rinq-go/src/internal/functest.NewPeer(0xc4203fd1c0, 0x11)
    	/home/kevin/go/src/github.com/rinq/rinq-go/src/internal/functest/peer.go:35 +0x185
    github.com/rinq/rinq-go/src/internal/remotesession_test.glob..func1.1()
    	/home/kevin/go/src/github.com/rinq/rinq-go/src/internal/remotesession/revision_functional_test.go:27 +0xd3
    github.com/rinq/rinq-go/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc42009e720, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    	/home/kevin/go/src/github.com/rinq/rinq-go/src/internal/remotesession/ginkgo_test.go:12 +0x64
    testing.tRunner(0xc4203780f0, 0xaa24e8)
    	/usr/lib/go-1.9/src/testing/testing.go:746 +0xd0
    created by testing.(*T).Run
    	/usr/lib/go-1.9/src/testing/testing.go:789 +0x2de
```

**Comment by jmalloc** [comment]
I noticed one from a previous discussion that was `815B.ntf`, so it's not exclusively response queues.

**Comment by koden-km** [comment]
This is the error i got on 4th test run, when running your new debug branch.
The full output was only small this time.
```
13:59 rinq/rinq-go 161-test-panic $ time make
go test  ./src/...
ok  	github.com/rinq/rinq-go/src/internal/attributes	0.066s
?   	github.com/rinq/rinq-go/src/internal/command	[no test files]
?   	github.com/rinq/rinq-go/src/internal/functest	[no test files]
?   	github.com/rinq/rinq-go/src/internal/localsession	[no test files]
ok  	github.com/rinq/rinq-go/src/internal/namespaces	0.012s
?   	github.com/rinq/rinq-go/src/internal/notify	[no test files]
ok  	github.com/rinq/rinq-go/src/internal/opentr	0.021s
ok  	github.com/rinq/rinq-go/src/internal/remotesession	4.917s
?   	github.com/rinq/rinq-go/src/internal/revisions	[no test files]
?   	github.com/rinq/rinq-go/src/internal/service	[no test files]
ok  	github.com/rinq/rinq-go/src/internal/x/bufferpool	0.010s
?   	github.com/rinq/rinq-go/src/internal/x/env	[no test files]
ok  	github.com/rinq/rinq-go/src/internal/x/repr	0.019s
?   	github.com/rinq/rinq-go/src/internal/x/syncx	[no test files]
Running Suite: rinq
===================
Random Seed: 1509508785
Will run 66 of 66 specs

••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
Ran 66 of 66 Specs in 0.001 seconds
SUCCESS! -- 66 Passed | 0 Failed | 0 Pending | 0 Skipped 2017/11/01 13:59:45 F7E8 connected to 'amqp://localhost' as 59F946B1-F7E8
2017/11/01 13:59:45 F7E8 started listening for command requests in 'my-api' namespace
2017/11/01 13:59:45 F7E8.1@0 session created
2017/11/01 13:59:45 F7E8 handled 'my-api::test' command from F7E8.1@0: 'my-api-error' failure (0ms 0/i 0/o) [59F946B1-F7E8.1@0#1]
2017/11/01 13:59:45 F7E8.1@0#1 called 'my-api::test' command: 'my-api-error' failure (0ms, 0/o 0/i) [59F946B1-F7E8.1@0#1]
2017/11/01 13:59:45 F7E8.1@0 session destroyed {}
2017/11/01 13:59:46 74CA connected to 'amqp://localhost' as 59F946B2-74CA
2017/11/01 13:59:46 74CA.1@0 session created
2017/11/01 13:59:46 74CA.1@0 session destroyed {}
2017/11/01 13:59:46 F236 connected to 'amqp://localhost' as 59F946B2-F236
2017/11/01 13:59:46 F236 started listening for command requests in 'math' namespace
2017/11/01 13:59:46 815B connected to 'amqp://localhost' as 59F946B2-815B
2017/11/01 13:59:46 815B.1@0 session created
2017/11/01 13:59:46 F236 handled 'math::add' command from 815B.1@0 successfully (1ms 14/i 1/o) [59F946B2-815B.1@0#1]
2017/11/01 13:59:46 815B.1@0#1 called 'math::add' command: success (5ms, 14/o 1/i) [59F946B2-815B.1@0#1]
2017/11/01 13:59:46 815B.1@0 session destroyed {}
2017/11/01 13:59:46 DC06 connected to 'amqp://localhost' as 59F946B2-DC06
--- FAIL: ExampleRevision_get (0.05s)
panic: Exception (405) Reason: "RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'DC06.req' in vhost '/'" [recovered]
	panic: Exception (405) Reason: "RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'DC06.req' in vhost '/'"

goroutine 1 [running]:
testing.runExample.func2(0xbe766f8c8c520d60, 0xff8d69f, 0xe3ed00, 0xc42000e4f8, 0xc42000e018, 0xc4202dbb00, 0xa8acca, 0x13, 0xaa34b8, 0xa8cea2, ...)
	/usr/lib/go-1.9/src/testing/example.go:117 +0x772
panic(0x9a9240, 0xc4201332a0)
	/usr/lib/go-1.9/src/runtime/panic.go:491 +0x283
github.com/rinq/rinq-go/src/rinq_test.ExampleRevision_get()
	/home/kevin/go/src/github.com/rinq/rinq-go/src/rinq/revision_example_test.go:20 +0x3da
testing.runExample(0xa8acca, 0x13, 0xaa34b8, 0xa8cea2, 0x16, 0x0, 0x0)
	/usr/lib/go-1.9/src/testing/example.go:122 +0x206
testing.runExamples(0xc420141ec8, 0xe24fe0, 0xa, 0xa, 0x840101)
	/usr/lib/go-1.9/src/testing/example.go:46 +0x15f
testing.(*M).Run(0xc420141f18, 0xc4202a1f70)
	/usr/lib/go-1.9/src/testing/testing.go:922 +0x18b
main.main()
	github.com/rinq/rinq-go/src/rinq/_test/_testmain.go:66 +0xdb
FAIL	github.com/rinq/rinq-go/src/rinq	0.327s
ok  	github.com/rinq/rinq-go/src/rinq/constraint	0.015s
ok  	github.com/rinq/rinq-go/src/rinq/ident	0.029s
ok  	github.com/rinq/rinq-go/src/rinq/options	0.008s
ok  	github.com/rinq/rinq-go/src/rinq/trace	0.007s
ok  	github.com/rinq/rinq-go/src/rinqamqp	2.914s
ok  	github.com/rinq/rinq-go/src/rinqamqp/internal/amqputil	0.017s
?   	github.com/rinq/rinq-go/src/rinqamqp/internal/commandamqp	[no test files]
?   	github.com/rinq/rinq-go/src/rinqamqp/internal/notifyamqp	[no test files]
artifacts/make/go.mk:89: recipe for target 'test' failed
make: *** [test] Error 1

real	0m6.977s
user	0m11.120s
sys	0m1.809s
```

**Comment by jmalloc** [comment]
My current best guess as to the cause due to the following combination of things:

1. RabbitMQ takes some non-zero amount of time to remove exclusive queues after the owning connection is closed.
1. We're generating peer IDs which are recycling the same random component. This is entirely reasonable and to be expected, as the random component is only 16 bits.
1. `rinqamqp.Dialer` generates a new peer ID after a `RESOURCE_LOCKED` exception occurs when declaring the "peer identity" queue (the one used to "reserve" the peer ID). The other exclusive queues (`<peer-id>.rsp`, `<peer-id>.ntf`, etc) are declared by their respective subsystems, where **it's assumed that because the "peer identity" queue declaration was successful that these ones will be too**.

We'd *probably* find that if we retried the queue declarations a few times they'd succeed as RMQ cleans up the queues with the same name from the previous peer. However, I think it would be clearer if we move the declaration of all peer-specific AMQP queues into the retry-loop that occurs in the dialer.

**Comment by jmalloc** [comment]
I'm still very curious as to why this doesn't occur for me.

**Comment by jmalloc** [comment]
Hacked the dialer to pre-declare all the exclusive queues in `161-test-panic` branch (see a2840cd).  If hypothesis above is correct, this will stop the errors.

**Comment by koden-km** [comment]
OK it took a few runs, but It eventually gave the error again.
Most tests are around ~12 seconds "user" time. This one was ~14.

```
21:27 rinq/rinq-go 161-test-panic $ time make
go test  ./src/...
ok  	github.com/rinq/rinq-go/src/internal/attributes	0.027s
?   	github.com/rinq/rinq-go/src/internal/command	[no test files]
?   	github.com/rinq/rinq-go/src/internal/functest	[no test files]
?   	github.com/rinq/rinq-go/src/internal/localsession	[no test files]
ok  	github.com/rinq/rinq-go/src/internal/namespaces	0.017s
?   	github.com/rinq/rinq-go/src/internal/notify	[no test files]
ok  	github.com/rinq/rinq-go/src/internal/opentr	0.020s
ok  	github.com/rinq/rinq-go/src/internal/remotesession	4.985s
?   	github.com/rinq/rinq-go/src/internal/revisions	[no test files]
?   	github.com/rinq/rinq-go/src/internal/service	[no test files]
ok  	github.com/rinq/rinq-go/src/internal/x/bufferpool	0.025s
?   	github.com/rinq/rinq-go/src/internal/x/env	[no test files]
ok  	github.com/rinq/rinq-go/src/internal/x/repr	0.015s
?   	github.com/rinq/rinq-go/src/internal/x/syncx	[no test files]
ok  	github.com/rinq/rinq-go/src/rinq	0.570s
ok  	github.com/rinq/rinq-go/src/rinq/constraint	0.033s
ok  	github.com/rinq/rinq-go/src/rinq/ident	0.018s
ok  	github.com/rinq/rinq-go/src/rinq/options	0.015s
ok  	github.com/rinq/rinq-go/src/rinq/trace	0.027s
Running Suite: amqp
===================
Random Seed: 1509535664
Will run 16 of 16 specs

2017/11/01 21:27:44 1CEE already registered, retrying with a different peer ID
2017/11/01 21:27:44 8AD6 connected to 'amqp://localhost' as 59F9AFB0-8AD6
2017/11/01 21:27:44 8AD6 invoker started (pre-fetch: 80)
2017/11/01 21:27:44 8AD6 server started with (pre-fetch: 8)
2017/11/01 21:27:44 8AD6 listener started (pre-fetch: 80)
2017/11/01 21:27:44 8AD6 notifier started
2017/11/01 21:27:44 8AD6 server stopped
2017/11/01 21:27:44 8AD6 listener stopped
2017/11/01 21:27:44 8AD6 invoker stopped
•2017/11/01 21:27:44 F7E8 connected to 'amqp://localhost' as 59F9AFB0-F7E8

------------------------------
•! Panic [0.056 seconds]
peer (functional)
/home/kevin/go/src/github.com/rinq/rinq-go/src/rinqamqp/peer_functional_test.go:15
  Session
  /home/kevin/go/src/github.com/rinq/rinq-go/src/rinqamqp/peer_functional_test.go:35
    returns a session that belongs to this peer [It]
    /home/kevin/go/src/github.com/rinq/rinq-go/src/rinqamqp/peer_functional_test.go:36

    Test Panicked
    Exception (405) Reason: "RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'F7E8.rsp' in vhost '/'"
    /usr/lib/go-1.9/src/runtime/panic.go:491

    Full Stack Trace
    	/usr/lib/go-1.9/src/runtime/panic.go:491 +0x283
    github.com/rinq/rinq-go/src/rinqamqp/internal/commandamqp.(*invoker).initialize(0xc4203d8270, 0xc42037eea0, 0xc4203c2600)
    	/home/kevin/go/src/github.com/rinq/rinq-go/src/rinqamqp/internal/commandamqp/invoker.go:235 +0x337
    github.com/rinq/rinq-go/src/rinqamqp/internal/commandamqp.newInvoker(0x59f9afb0, 0xc42039f7e8, 0x50, 0x12a05f200, 0xc4203cc440, 0xc42039e280, 0xd5e460, 0xc420011e60, 0xd5d2e0, 0xc420011db0, ...)
    	/home/kevin/go/src/github.com/rinq/rinq-go/src/rinqamqp/internal/commandamqp/invoker.go:87 +0x464
    github.com/rinq/rinq-go/src/rinqamqp/internal/commandamqp.New(0x59f9afb0, 0xc42036f7e8, 0x12a05f200, 0xd5d2e0, 0xc420011db0, 0x8, 0x50, 0x29e8d60800, 0x0, 0x0, ...)
    	/home/kevin/go/src/github.com/rinq/rinq-go/src/rinqamqp/internal/commandamqp/factory.go:32 +0x1c3
    github.com/rinq/rinq-go/src/rinqamqp.(*Dialer).Dial(0xc4200b9188, 0xd5f620, 0xc42001a1b8, 0xa81be5, 0x10, 0xc4200b9278, 0x1, 0x1, 0x0, 0x0, ...)
    	/home/kevin/go/src/github.com/rinq/rinq-go/src/rinqamqp/dialer.go:188 +0x6b6
    github.com/rinq/rinq-go/src/rinqamqp.DialEnv(0xc4200b9278, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
    	/home/kevin/go/src/github.com/rinq/rinq-go/src/rinqamqp/dialer.go:106 +0x322
    github.com/rinq/rinq-go/src/internal/functest.NewPeer(0x0, 0x0)
    	/home/kevin/go/src/github.com/rinq/rinq-go/src/internal/functest/peer.go:33 +0x12f
    github.com/rinq/rinq-go/src/internal/functest.SharedPeer(0x0, 0x0)
    	/home/kevin/go/src/github.com/rinq/rinq-go/src/internal/functest/peer.go:19 +0x38
    github.com/rinq/rinq-go/src/rinqamqp_test.glob..func1.4.1()
    	/home/kevin/go/src/github.com/rinq/rinq-go/src/rinqamqp/peer_functional_test.go:37 +0x34
    github.com/rinq/rinq-go/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc420164780, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    	/home/kevin/go/src/github.com/rinq/rinq-go/src/rinqamqp/ginkgo_test.go:12 +0x64
    testing.tRunner(0xc42033a0f0, 0xa9b980)
    	/usr/lib/go-1.9/src/testing/testing.go:746 +0xd0
    created by testing.(*T).Run
    	/usr/lib/go-1.9/src/testing/testing.go:789 +0x2de
    
------------------------------

----------8<----------8<----------8<----------8<----------8<----------
... many lines of test output ...
----------8<----------8<----------8<----------8<----------8<----------

•

Summarizing 1 Failure:

[Panic!] peer (functional) Session [It] returns a session that belongs to this peer 
/usr/lib/go-1.9/src/runtime/panic.go:491

Ran 16 of 16 Specs in 2.384 seconds
FAIL! -- 15 Passed | 1 Failed | 0 Pending | 0 Skipped --- FAIL: TestSuite (2.38s)
2017/11/01 21:27:46 10DA connected to 'amqp://localhost' as 59F9AFB2-10DA
2017/11/01 21:27:46 CA54 connected to 'amqp://localhost' as 59F9AFB2-CA54
2017/11/01 21:27:46 1150 connected to 'amqp://localhost' as 59F9AFB2-1150
FAIL
FAIL	github.com/rinq/rinq-go/src/rinqamqp	2.589s
ok  	github.com/rinq/rinq-go/src/rinqamqp/internal/amqputil	0.018s
?   	github.com/rinq/rinq-go/src/rinqamqp/internal/commandamqp	[no test files]
?   	github.com/rinq/rinq-go/src/rinqamqp/internal/notifyamqp	[no test files]
artifacts/make/go.mk:89: recipe for target 'test' failed
make: *** [test] Error 1

real	0m7.756s
user	0m14.191s
sys	0m2.225s
```

**Comment by koden-km** [comment]
I just ran it again in the test loop and had the errors 3 test runs in a row.
I had the RabbitMQ interface open this time. They do seem to cleanup pretty quick. The UI is set to the 5 second update. When it does get the error, the queue seems to stay in the UI longer though.

**Comment by jmalloc** [comment]
My hax were so haxy that it behaved exactly the same as before! Try now ;)

**Comment by koden-km** [comment]
The new branch change seems good, no errors now.

**Comment by jmalloc** [comment]
Hey dude, reckon you could try to reproduce this again when you get a chance... just run tests in a loop (from `master`, not this branch), then if you can reproduce, try this branch again.
